<a href="https://colab.research.google.com/github/mohsanjaved619/network-intrusion-detection/blob/main/01_data_understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RT-IoT2022 Network Intrusion Detection

## 01 - Data Understanding

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('/content/sample_data/RT_IOT2022')

In [63]:
df.head(5000)

,Unnamed: 0,id.orig_p,id.resp_p,proto,service,flow_duration,fwd_pkts_tot,bwd_pkts_tot,fwd_data_pkts_tot,bwd_data_pkts_tot,fwd_pkts_per_sec,bwd_pkts_per_sec,flow_pkts_per_sec,down_up_ratio,fwd_header_size_tot,fwd_header_size_min,fwd_header_size_max,bwd_header_size_tot,bwd_header_size_min,bwd_header_size_max,flow_FIN_flag_count,flow_SYN_flag_count,flow_RST_flag_count,fwd_PSH_flag_count,bwd_PSH_flag_count,flow_ACK_flag_count,fwd_URG_flag_count,bwd_URG_flag_count,flow_CWR_flag_count,flow_ECE_flag_count,fwd_pkts_payload.min,fwd_pkts_payload.max,fwd_pkts_payload.tot,fwd_pkts_payload.avg,fwd_pkts_payload.std,bwd_pkts_payload.min,bwd_pkts_payload.max,bwd_pkts_payload.tot,bwd_pkts_payload.avg,bwd_pkts_payload.std,flow_pkts_payload.min,flow_pkts_payload.max,flow_pkts_payload.tot,flow_pkts_payload.avg,flow_pkts_payload.std,fwd_iat.min,fwd_iat.max,fwd_iat.tot,fwd_iat.avg,fwd_iat.std,bwd_iat.min,bwd_iat.max,bwd_iat.tot,bwd_iat.avg,bwd_iat.std,flow_iat.min,flow_iat.max,flow_iat.tot,flow_iat.avg,flow_iat.std,payload_bytes_per_second,fwd_subflow_pkts,bwd_subflow_pkts,fwd_subflow_bytes,bwd_subflow_bytes,fwd_bulk_bytes,bwd_bulk_bytes,fwd_bulk_packets,bwd_bulk_packets,fwd_bulk_rate,bwd_bulk_rate,active.min,active.max,active.tot,active.avg,active.std,idle.min,idle.max,idle.tot,idle.avg,idle.std,fwd_init_window_size,bwd_init_window_size,fwd_last_window_size,Attack_type
0,0,38667,1883,tcp,mqtt,32.011598,9,5,3,3,0.281148,0.156193,0.437341,0.555556,296,32,40,168,32,40,0,2,1,3,3,13,0,0,0,0,0.0,33.0,76.0,8.444444,13.115936,0.0,23.0,32.0,6.4,9.555103,0.0,33.0,108.0,7.714286,11.618477,761.985779,2.972918e+07,3.201160e+07,4.001450e+06,1.040307e+07,4438.877106,1.511694e+06,2.026391e+06,506597.757339,680406.147126,761.985779,2.972918e+07,3.201160e+07,2.462431e+06,8.199747e+06,3.373777,3.0,1.666667,25.333333,10.666667,0.0,0.0,0.0,0.0,0.0,0.0,2.282415e+06,2.282415e+06,2.282415e+06,2.282415e+06,0.0,2.972918e+07,2.972918e+07,2.972918e+07,2.972918e+07,0.0,64240,26847,502,MQTT_Publish
1,1,51143,1883,tcp,mqtt,31.883584,9,5,3,3,0.282277,0.156821,0.439097,0.555556,296,32,40,168,32,40,0,2,1,3,3,13,0,0,0,0,0.0,33.0,76.0,8.444444,13.115936,0.0,23.0,32.0,6.4,9.555103,0.0,33.0,108.0,7.714286,11.618477,247.001648,2.985528e+07,3.188358e+07,3.985448e+06,1.046346e+07,4214.048386,1.576436e+06,1.876261e+06,469065.248966,741351.686212,247.001648,2.985528e+07,3.188358e+07,2.452583e+06,8.242459e+06,3.387323,3.0,1.666667,25.333333,10.666667,0.0,0.0,0.0,0.0,0.0,0.0,2.028307e+06,2.028307e+06,2.028307e+06,2.028307e+06,0.0,2.985528e+07,2.985528e+07,2.985528e+07,2.985528e+07,0.0,64240,26847,502,MQTT_Publish
2,2,44761,1883,tcp,mqtt,32.124053,9,5,3,3,0.280164,0.155647,0.435811,0.555556,296,32,40,168,32,40,0,2,1,3,3,13,0,0,0,0,0.0,33.0,74.0,8.222222,12.852799,0.0,21.0,30.0,6.0,8.689074,0.0,33.0,104.0,7.428571,11.229866,283.956528,2.984215e+07,3.212405e+07,4.015507e+06,1.044238e+07,2456.903458,1.476049e+06,2.013770e+06,503442.466259,660344.360027,283.956528,2.984215e+07,3.212405e+07,2.471081e+06,8.230593e+06,3.237450,3.0,1.666667,24.666667,10.000000,0.0,0.0,0.0,0.0,0.0,0.0,2.281904e+06,2.281904e+06,2.281904e+06,2.281904e+06,0.0,2.984215e+07,2.984215e+07,2.984215e+07,2.984215e+07,0.0,64240,26847,502,MQTT_Publish
3,3,60893,1883,tcp,mqtt,31.961063,9,5,3,3,0.281593,0.156440,0.438033,0.555556,296,32,40,168,32,40,0,2,1,3,3,13,0,0,0,0,0.0,33.0,74.0,8.222222,12.852799,0.0,21.0,30.0,6.0,8.689074,0.0,33.0,104.0,7.428571,11.229866,288.963318,2.991377e+07,3.196106e+07,3.995133e+06,1.048253e+07,3933.906555,1.551892e+06,1.883784e+06,470946.013927,724569.317911,288.963318,2.991377e+07,3.196106e+07,2.458543e+06,8.257786e+06,3.253959,3.0,1.666667,24.666667,10.000000,0.0,0.0,0.0,0.0,0.0,0.0,2.047288e+06,2.047288e+06,2.047288e+06,2.047288e+06,0.0,2.991377e+07,2.991377e+07,2.991377e+07,2.991377e+07,0.0,64240,26847,502,MQTT_Publish
4,4,51087,1883,tcp,mqtt,31.902362,9,5,3,3,0.282111,0.156728,0.438839,0.555556,296,32,40,168,32,40,0,2,1,3,3,13,0,0,0,0,0.0,33.0,76.0,8.444444,13.115936,0.0,23.0,32.0,6.4,9.555103,0.0,33.0,108.0,7.714286,11.618477,387.907028,2.981470e+07,3.190236e+07,3.987795e+06,1.044702e+07,3005.027771,1.632083e+06,1.935984e+06,483996.033669,768543.390313,387.907028,2.981470e+07,3.190236e+07,2.454028e+06,8.230584e+06,3.385329,3.0,1.666667,25.333333,10.666667,0.0,0.0,0.0,0.0,0.0,0.0,2.087657e+06,2.087657e+06,2.087657e+06,2.087657e+06,0.0,2.981470e+07,2.981470e+07,2.981470e+07,2.981470e+07,0.0,64240,26847,502,MQTT_Publish
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,849,3,3,icmp,-,0.000000,1,0,1,0,0.000000,0.000000,0.000000,0.000000,8,8,8,0,0,0,0,0,0,0,0,0,0,0,0,0,28.0,28.0,28.0,28.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,28.0,28.0,28.0,28.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.0,0.000000,28.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0,0,0,Thing_Speak
4996,850,38400,80,tcp,http,0.923743,7,5,2,1,7.577865,5.412761,12.990626,0.714286,232,32,40,168,32,40,2,2,0,2,1,11,0,0,0,0,0.0,169.0,215.0,30.714286,63.342230,0.0,538.0,538.0,107.6,240.600914,0.0,538.0,753.0,62.750000,157.500433,92.029572,3.158309e+05,9.254532e+05,1.542422e+05,1.680289e+05,72.002411,3.066149e+05,6.230829e+05,155770.719100,168228.311900,72.002411,3.026021e+05,9.254532e+05,8.413211e+04,1.380670e+05,815.161784,7.0,5.000000,215.000000,538.000000,0.0,0.0,0.0,0.0,0.0,0.0,9.254532e+05,9.254532e+05,9.254532e+05,9.254532e+05,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,64240,26847,501,Thing_Speak
4997,851,36275,53,udp,dns,0.058309,2,2,2,2,34.299976,34.299976,68.599953,1.000000,16,8,8,16,8,8,0,0,0,0,0,0,0,0,0,0,36.0,36.0,72.0,36.000000,0.000000,36.0,68.0,104.0,52.0,22.627417,36.0,68.0,176.0,44.000000,16.000000,889.062881,8.890629e+02,8.890629e+02,8.890629e+02,0.000000e+00,57187.080380,5.718708e+04,5.718708e+04,57187.080380,0.000000,232.934952,5.718708e+04,5.830908e+04,1.943636e+04,3.269473e+04,3018.397913,2.0,2.000000,72.000000,104.000000,0.0,0.0,0.0,0.0,0.0,0.0,5.830908e+04,5.830908e+04,5.830908e+04,5.830908e+04,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0,0,0,Thing_Speak
4998,852,32782,80,tcp,http,0.733338,7,5,2,1,9.545392,6.818137,16.363530,0.714286,232,32,40,168,32,40,2,2,0,2,1,11,0,0,0,0,0.0,169.0,215.0,30.714286,63.342230,0.0,538.0,538.0,107.6,240.600914,0.0,538.0,753.0,62.750000,157.500433,91.075897,2.678261e+05,7.350690e+05,1.225115e+05,1.337987e+05,61.988831,2.356901e+05,5.039160e+05,125979.006300,125376.378300,61.988831,2.314770e+05,7.350690e+05,6.682446e+04,1.054391e+05,1026.811483,7.0,5.000000,215.000000,538.000000,0.0,0.0,0.0,0.0,0.0,0.0,7.350690e+05,7.350690e+05,7.350690e+05,7.350690e+05,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,64240,26847,501,Thing_Speak
4999,853,48263,53,udp,dns,0.043983,2,2,2,2,45.472132,45.472132,90.944264,1.000000,16,8,8,16,8,8,0,0,0,0,0,0,0,0,0,0,36.0,36.0,72.0,36.000000,0.000000,68.0,120.0,188.0,94.0,36.769553,36.0,120.0,260.0,65.000000,39.648455,238.895416,2.388954e+02,2.388954e+02,2.388954e+02,0.000000e+00,4034.996033,4.034996e+03,4.034996e+03,4034.996033,0.000000,238.895416,3.970909e+04,4.398298e+04,1.466099e+04,2.177517e+04,5911.377183,2.0,2.000000,72.000000,188.000000,0.0,0.0,0.0,0.0,0.0,0.0,4.398298e+04,4.398298e+04,4.398298e+04,4.398298e+04,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0,0,0,Thing_Speak

In [7]:
df.shape

(123117, 85)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123117 entries, 0 to 123116
Data columns (total 85 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0                123117 non-null  int64
 1   id.orig_p                 123117 non-null  int64
 2   id.resp_p                 123117 non-null  int64
 3   proto                     123117 non-null  object
 4   service                   123117 non-null  object
 5   flow_duration             123117 non-null  float64
 6   fwd_pkts_tot              123117 non-null  int64
 7   bwd_pkts_tot              123117 non-null  int64
 8   fwd_data_pkts_tot         123117 non-null  int64
 9   bwd_data_pkts_tot         123117 non-null  int64
 10  fwd_pkts_per_sec          123117 non-null  float64
 11  bwd_pkts_per_sec          123117 non-null  float64
 12  flow_pkts_per_sec         123117 non-null  float64
 13  down_up_ratio             123117 non-null  float64
 14  fwd_header_size_tot       123117 non-null  int64
 15  fwd_header_size_min       123117 non-null  int64
 16  fwd_header_size_max       123117 non-null  int64
 17  bwd_header_size_tot       123117 non-null  int64
 18  bwd_header_size_min       123117 non-null  int64
 19  bwd_header_size_max       123117 non-null  int64
 20  flow_FIN_flag_count       123117 non-null  int64
 21  flow_SYN_flag_count       123117 non-null  int64
 22  flow_RST_flag_count       123117 non-null  int64
 23  fwd_PSH_flag_count        123117 non-null  int64
 24  bwd_PSH_flag_count        123117 non-null  int64
 25  flow_ACK_flag_count       123117 non-null  int64
 26  fwd_URG_flag_count        123117 non-null  int64
 27  bwd_URG_flag_count        123117 non-null  int64
 28  flow_CWR_flag_count       123117 non-null  int64
 29  flow_ECE_flag_count       123117 non-null  int64
 30  fwd_pkts_payload.min      123117 non-null  float64
 31  fwd_pkts_payload.max      123117 non-null  float64
 32  fwd_pkts_payload.tot      123117 non-null  float64
 33  fwd_pkts_payload.avg      123117 non-null  float64
 34  fwd_pkts_payload.std      123117 non-null  float64
 35  bwd_pkts_payload.min      123117 non-null  float64
 36  bwd_pkts_payload.max      123117 non-null  float64
 37  bwd_pkts_payload.tot      123117 non-null  float64
 38  bwd_pkts_payload.avg      123117 non-null  float64
 39  bwd_pkts_payload.std      123117 non-null  float64
 40  flow_pkts_payload.min     123117 non-null  float64
 41  flow_pkts_payload.max     123117 non-null  float64
 42  flow_pkts_payload.tot     123117 non-null  float64
 43  flow_pkts_payload.avg     123117 non-null  float64
 44  flow_pkts_payload.std     123117 non-null  float64
 45  fwd_iat.min               123117 non-null  float64
 46  fwd_iat.max               123117 non-null  float64
 47  fwd_iat.tot               123117 non-null  float64
 48  fwd_iat.avg               123117 non-null  float64
 49  fwd_iat.std               123117 non-null  float64
 50  bwd_iat.min               123117 non-null  float64
 51  bwd_iat.max               123117 non-null  float64
 52  bwd_iat.tot               123117 non-null  float64
 53  bwd_iat.avg               123117 non-null  float64
 54  bwd_iat.std               123117 non-null  float64
 55  flow_iat.min              123117 non-null  float64
 56  flow_iat.max              123117 non-null  float64
 57  flow_iat.tot              123117 non-null  float64
 58  flow_iat.avg              123117 non-null  float64
 59  flow_iat.std              123117 non-null  float64
 60  payload_bytes_per_second  123117 non-null  float64
 61  fwd_subflow_pkts          123117 non-null  float64
 62  bwd_subflow_pkts          123117 non-null  float64
 63  fwd_subflow_bytes         123117 non-null  float64
 64  bwd_subflow_bytes         123117 non-null  float64
 65  fwd_bulk_bytes            123117 non-null  float64
 66  bwd_bulk_bytes            123117 non-null  float64
 67  fwd_bulk_packets          123117 non-null  float64
 68  bwd_bulk_packets          123117 non-null  float64
 69  fwd_bulk_rate             123117 non-null  float64
 70  bwd_bulk_rate             123117 non-null  float64
 71  active.min                123117 non-null  float64
 72  active.max                123117 non-null  float64
 73  active.tot                123117 non-null  float64
 74  active.avg                123117 non-null  float64
 75  active.std                123117 non-null  float64
 76  idle.min                  123117 non-null  float64
 77  idle.max                  123117 non-null  float64
 78  idle.tot                  123117 non-null  float64
 79  idle.avg                  123117 non-null  float64
 80  idle.std                  123117 non-null  float64
 81  fwd_init_window_size      123117 non-null  int64
 82  bwd_init_window_size      123117 non-null  int64
 83  fwd_last_window_size      123117 non-null  int64
 84  Attack_type               123117 non-null  object
dtypes: float64(56), int64(26), object(3)
memory usage: 79.8+ MB

In [18]:
df.isnull().sum().sum()

np.int64(0)

In [31]:
df['Attack_type'].value_counts()

Attack_type
DOS_SYN_Hping                 94659
Thing_Speak                    8108
ARP_poisioning                 7750
MQTT_Publish                   4146
NMAP_UDP_SCAN                  2590
NMAP_XMAS_TREE_SCAN            2010
NMAP_OS_DETECTION              2000
NMAP_TCP_scan                  1002
DDOS_Slowloris                  534
Wipro_bulb                      253
Metasploit_Brute_Force_SSH       37
NMAP_FIN_SCAN                    28
Name: count, dtype: int64

## 02 - Column Investigation

In [35]:
print(list(df))

['Unnamed: 0', 'id.orig_p', 'id.resp_p', 'proto', 'service', 'flow_duration', 'fwd_pkts_tot', 'bwd_pkts_tot', 'fwd_data_pkts_tot', 'bwd_data_pkts_tot', 'fwd_pkts_per_sec', 'bwd_pkts_per_sec', 'flow_pkts_per_sec', 'down_up_ratio', 'fwd_header_size_tot', 'fwd_header_size_min', 'fwd_header_size_max', 'bwd_header_size_tot', 'bwd_header_size_min', 'bwd_header_size_max', 'flow_FIN_flag_count', 'flow_SYN_flag_count', 'flow_RST_flag_count', 'fwd_PSH_flag_count', 'bwd_PSH_flag_count', 'flow_ACK_flag_count', 'fwd_URG_flag_count', 'bwd_URG_flag_count', 'flow_CWR_flag_count', 'flow_ECE_flag_count', 'fwd_pkts_payload.min', 'fwd_pkts_payload.max', 'fwd_pkts_payload.tot', 'fwd_pkts_payload.avg', 'fwd_pkts_payload.std', 'bwd_pkts_payload.min', 'bwd_pkts_payload.max', 'bwd_pkts_payload.tot', 'bwd_pkts_payload.avg', 'bwd_pkts_payload.std', 'flow_pkts_payload.min', 'flow_pkts_payload.max', 'flow_pkts_payload.tot', 'flow_pkts_payload.avg', 'flow_pkts_payload.std', 'fwd_iat.min', 'fwd_iat.max', 'fwd_iat.tot', 'fwd_iat.avg', 'fwd_iat.std', 'bwd_iat.min', 'bwd_iat.max', 'bwd_iat.tot', 'bwd_iat.avg', 'bwd_iat.std', 'flow_iat.min', 'flow_iat.max', 'flow_iat.tot', 'flow_iat.avg', 'flow_iat.std', 'payload_bytes_per_second', 'fwd_subflow_pkts', 'bwd_subflow_pkts', 'fwd_subflow_bytes', 'bwd_subflow_bytes', 'fwd_bulk_bytes', 'bwd_bulk_bytes', 'fwd_bulk_packets', 'bwd_bulk_packets', 'fwd_bulk_rate', 'bwd_bulk_rate', 'active.min', 'active.max', 'active.tot', 'active.avg', 'active.std', 'idle.min', 'idle.max', 'idle.tot', 'idle.avg', 'idle.std', 'fwd_init_window_size', 'bwd_init_window_size', 'fwd_last_window_size', 'Attack_type']

In [39]:
df['service'].unique()

array(['mqtt', '-', 'http', 'dns', 'ntp', 'ssl', 'dhcp', 'irc', 'ssh',
       'radius'], dtype=object)

In [40]:
df['proto'].unique()

array(['tcp', 'udp', 'icmp'], dtype=object)

In [41]:
df['Attack_type'].unique()

array(['MQTT_Publish', 'Thing_Speak', 'Wipro_bulb', 'ARP_poisioning',
       'DDOS_Slowloris', 'DOS_SYN_Hping', 'Metasploit_Brute_Force_SSH',
       'NMAP_FIN_SCAN', 'NMAP_OS_DETECTION', 'NMAP_TCP_scan',
       'NMAP_UDP_SCAN', 'NMAP_XMAS_TREE_SCAN'], dtype=object)

In [65]:
df['Unnamed: 0'].unique()

array([    0,     1,     2, ..., 94656, 94657, 94658])

In [66]:
df_mod = df.drop(columns='Unnamed: 0')

In [68]:
df['service'].value_counts()

service
-         102861
dns         9753
mqtt        4132
http        3464
ssl         2663
ntp          121
dhcp          50
irc           43
ssh           28
radius         2
Name: count, dtype: int64

In [69]:
df['proto'].value_counts()

proto
tcp     110427
udp      12633
icmp        57
Name: count, dtype: int64

In [72]:
df_num = df.drop(columns=['service', 'proto', 'Attack_type', 'Unnamed: 0'])

In [75]:
df_num.value_counts()

id.orig_p  id.resp_p  flow_duration  fwd_pkts_tot  bwd_pkts_tot  fwd_data_pkts_tot  bwd_data_pkts_tot  fwd_pkts_per_sec  bwd_pkts_per_sec  flow_pkts_per_sec  down_up_ratio  fwd_header_size_tot  fwd_header_size_min  fwd_header_size_max  bwd_header_size_tot  bwd_header_size_min  bwd_header_size_max  flow_FIN_flag_count  flow_SYN_flag_count  flow_RST_flag_count  fwd_PSH_flag_count  bwd_PSH_flag_count  flow_ACK_flag_count  fwd_URG_flag_count  bwd_URG_flag_count  flow_CWR_flag_count  flow_ECE_flag_count  fwd_pkts_payload.min  fwd_pkts_payload.max  fwd_pkts_payload.tot  fwd_pkts_payload.avg  fwd_pkts_payload.std  bwd_pkts_payload.min  bwd_pkts_payload.max  bwd_pkts_payload.tot  bwd_pkts_payload.avg  bwd_pkts_payload.std  flow_pkts_payload.min  flow_pkts_payload.max  flow_pkts_payload.tot  flow_pkts_payload.avg  flow_pkts_payload.std  fwd_iat.min  fwd_iat.max  fwd_iat.tot  fwd_iat.avg  fwd_iat.std  bwd_iat.min  bwd_iat.max  bwd_iat.tot  bwd_iat.avg  bwd_iat.std  flow_iat.min  flow_iat.max  flow_iat.tot  flow_iat.avg  flow_iat.std  payload_bytes_per_second  fwd_subflow_pkts  bwd_subflow_pkts  fwd_subflow_bytes  bwd_subflow_bytes  fwd_bulk_bytes  bwd_bulk_bytes  fwd_bulk_packets  bwd_bulk_packets  fwd_bulk_rate  bwd_bulk_rate  active.min  active.max  active.tot  active.avg  active.std  idle.min  idle.max  idle.tot  idle.avg  idle.std  fwd_init_window_size  bwd_init_window_size  fwd_last_window_size
5353       5353       0.000000       1             0             1                  0                  0.000000          0.000000          0.000000           0.0            8                    8                    8                    0                    0                    0                    0                    0                    0                    0                   0                   0                    0                   0                   0                    0                    45.0                  45.0                  45.0                  45.0                  0.0                   0.0                   0.0                   0.0                   0.0                   0.0                   45.0                   45.0                   45.0                   45.0                   0.000000               0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.000000      0.000000      0.000000      0.000000      0.0           0.000000e+00              1.0               0.0               45.0               0.0                0.0             0.0             0.0               0.0               0.0            0.0            0.000000    0.000000    0.000000    0.000000    0.0         0.0       0.0       0.0       0.0       0.0       0                     0                     0                       75
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         115.0                 115.0                 115.0                 115.0                 0.0                   0.0                   0.0                   0.0                   0.0                   0.0                   115.0                  115.0                  115.0                  115.0                  0.000000               0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.000000      0.000000      0.000000      0.000000      0.0           0.000000e+00              1.0               0.0               115.0              0.0                0.0             0.0             0.0               0.0               0.0            0.0            0.000000    0.000000    0.000000    0.000000    0.0         0.0       0.0       0.0       0.0       0.0       0                     0                     0                       24
133        134        0.000000       1             0             1                  0                  0.000000          0.000000          0.000000           0.0            8                    8                    8                    0                    0                    0                    0                    0                    0                    0                   0                   0                    0                   0                   0                    0                    8.0                   8.0                   8.0                   8.0                   0.0                   0.0                   0.0                   0.0                   0.0                   0.0                   8.0                    8.0                    8.0                    8.0                    0.000000               0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.000000      0.000000      0.000000      0.000000      0.0           0.000000e+00              1.0               0.0               8.0                0.0                0.0             0.0             0.0               0.0               0.0            0.0            0.000000    0.000000    0.000000    0.000000    0.0         0.0       0.0       0.0       0.0       0.0       0                     0                     0                       18
68         67         0.000000       0             1             0                  1                  0.000000          0.000000          0.000000           0.0            0                    0                    0                    8                    8                    8                    0                    0                    0                    0                   0                   0                    0                   0                   0                    0                    0.0                   0.0                   0.0                   0.0                   0.0                   548.0                 548.0                 548.0                 548.0                 0.0                   548.0                  548.0                  548.0                  548.0                  0.000000               0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.000000      0.000000      0.000000      0.000000      0.0           0.000000e+00              0.0               1.0               0.0                548.0              0.0             0.0             0.0               0.0               0.0            0.0            0.000000    0.000000    0.000000    0.000000    0.0         0.0       0.0       0.0       0.0       0.0       0                     0                     0                       17
5353       5353       0.000000       1             0             1                  0                  0.000000          0.000000          0.000000           0.0            8                    8                    8                    0                    0                    0                    0                    0                    0                    0                   0                   0                    0                   0                   0                    0                    158.0                 158.0                 158.0                 158.0                 0.0                   0.0                   0.0                   0.0                   0.0                   0.0                   158.0                  158.0                  158.0                  158.0                  0.000000               0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.000000      0.000000      0.000000      0.000000      0.0           0.000000e+00              1.0               0.0               158.0              0.0                0.0             0.0             0.0               0.0               0.0            0.0            0.000000    0.000000    0.000000    0.000000    0.0         0.0       0.0       0.0       0.0       0.0       0                     0                     0                       11
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ..
26556      21         0.000000       1             0             1                  0                  0.000000          0.000000          0.000000           0.0            20                   20                   20                   0                    0                    0                    0                    1                    0                    0                   0                   0                    0                   0                   0                    0                    120.0                 120.0                 120.0                 120.0                 0.0                   0.0                   0.0                   0.0                   0.0                   0.0                   120.0                  120.0                  120.0                  120.0                  0.000000               0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.000000      0.000000      0.000000      0.000000      0.0           0.000000e+00              1.0               0.0               120.0              0.0                0.0             0.0             0.0               0.0               0.0            0.0            0.000000    0.000000    0.000000    0.000000    0.0         0.0       0.0       0.0       0.0       0.0       64                    0                     64                       1
26555      21         0.000005       1             1             1                  0                  199728.761905     199728.761905     399457.523810      1.0            20                   20                   20                   20                   20                   20                   0                    1                    1                    0                   0                   1                    0                   0                   0                    0                    120.0                 120.0                 120.0                 120.0                 0.0                   0.0                   0.0                   0.0                   0.0                   0.0                   0.0                    120.0                  120.0                  60.0                   84.852814              0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          5.006790      5.006790      5.006790      5.006790      0.0           2.396745e+07              1.0               1.0               120.0              0.0                0.0             0.0             0.0               0.0               0.0            0.0            5.006790    5.006790    5.006790    5.006790    0.0         0.0       0.0       0.0       0.0       0.0       64                    0                     64                       1
26554      21         0.000004       1             1             1                  0                  246723.764706     246723.764706     493447.529412      1.0            20                   20                   20                   20                   20                   20                   0                    1                    1                    0                   0                   1                    0                   0                   0                    0                    120.0                 120.0                 120.0                 120.0                 0.0                   0.0                   0.0                   0.0                   0.0                   0.0                   0.0                    120.0                  120.0                  60.0                   84.852814              0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          4.053116      4.053116      4.053116      4.053116      0.0           2.960685e+07              1.0               1.0               120.0              0.0                0.0             0.0             0.0               0.0               0.0            0.0            4.053116    4.053116    4.053116    4.053116    0.0         0.0       0.0       0.0       0.0       0.0       64                    0                     64                       1
26553      21         0.000008       1             1             1                  0                  123361.882353     123361.882353     246723.764706      1.0            20                   20                   20                   20                   20                   20                   0                    1                    1                    0                   0                   1                    0                   0                   0                    0                    120.0                 120.0                 120.0                 120.0                 0.0                   0.0                   0.0                   0.0                   0.0                   0.0                   0.0                    120.0                  120.0                  60.0                   84.852814              0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          8.106232      8.106232      8.106232      8.106232      0.0           1.480343e+07              1.0               1.0               120.0              0.0                0.0             0.0             0.0               0.0               0.0            0.0            8.106232    8.106232    8.106232    8.106232    0.0         0.0       0.0       0.0       0.0       0.0       64                    0                     64                       1
26565      21         0.000005       1             1             1                  0                  199728.761905     199728.761905     399457.523810      1.0            20                   20                   20                   20                   20                   20                   0                    1                    1                    0                   0                   1                    0                   0                   0                    0                    120.0                 120.0                 120.0                 120.0                 0.0                   0.0                   0.0                   0.0                   0.0                   0.0                   0.0                    120.0                  120.0                  60.0                   84.852814              0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          0.0          5.006790      5.006790      5.006790      5.006790      0.0           2.396745e+07              1.0               1.0               120.0              0.0                0.0             0.0             0.0               0.0               0.0            0.0            5.006790    5.006790    5.006790    5.006790    0.0         0.0       0.0       0.0       0.0       0.0       64                    0                     64                       1
Name: count, Length: 117915, dtype: int64

In [81]:
df_num[['flow_duration', 'fwd_pkts_tot', 'bwd_pkts_tot', 'fwd_data_pkts_tot', 'bwd_data_pkts_tot', 'fwd_pkts_per_sec', 'bwd_pkts_per_sec', 'flow_pkts_per_sec', 'down_up_ratio', 'fwd_header_size_tot', 'fwd_header_size_min', 'fwd_header_size_max', 'bwd_header_size_tot', 'bwd_header_size_min', 'bwd_header_size_max', 'flow_FIN_flag_count', 'flow_SYN_flag_count', 'flow_RST_flag_count', 'fwd_PSH_flag_count', 'bwd_PSH_flag_count', 'flow_ACK_flag_count', 'fwd_URG_flag_count', 'bwd_URG_flag_count', 'flow_CWR_flag_count', 'flow_ECE_flag_count', 'fwd_pkts_payload.min', 'fwd_pkts_payload.max', 'fwd_pkts_payload.tot', 'fwd_pkts_payload.avg', 'fwd_pkts_payload.std', 'bwd_pkts_payload.min', 'bwd_pkts_payload.max', 'bwd_pkts_payload.tot', 'bwd_pkts_payload.avg', 'bwd_pkts_payload.std', 'flow_pkts_payload.min', 'flow_pkts_payload.max', 'flow_pkts_payload.tot', 'flow_pkts_payload.avg', 'flow_pkts_payload.std', 'fwd_iat.min', 'fwd_iat.max', 'fwd_iat.tot', 'fwd_iat.avg', 'fwd_iat.std', 'bwd_iat.min', 'bwd_iat.max', 'bwd_iat.tot', 'bwd_iat.avg', 'bwd_iat.std', 'flow_iat.min', 'flow_iat.max', 'flow_iat.tot', 'flow_iat.avg', 'flow_iat.std', 'payload_bytes_per_second', 'fwd_subflow_pkts', 'bwd_subflow_pkts', 'fwd_subflow_bytes', 'bwd_subflow_bytes', 'fwd_bulk_bytes', 'bwd_bulk_bytes', 'fwd_bulk_packets', 'bwd_bulk_packets', 'fwd_bulk_rate', 'bwd_bulk_rate', 'active.min', 'active.max', 'active.tot', 'active.avg', 'active.std', 'idle.min', 'idle.max', 'idle.tot', 'idle.avg', 'idle.std', 'fwd_init_window_size', 'bwd_init_window_size', 'fwd_last_window_size']].describe()

,flow_duration,fwd_pkts_tot,bwd_pkts_tot,fwd_data_pkts_tot,bwd_data_pkts_tot,fwd_pkts_per_sec,bwd_pkts_per_sec,flow_pkts_per_sec,down_up_ratio,fwd_header_size_tot,fwd_header_size_min,fwd_header_size_max,bwd_header_size_tot,bwd_header_size_min,bwd_header_size_max,flow_FIN_flag_count,flow_SYN_flag_count,flow_RST_flag_count,fwd_PSH_flag_count,bwd_PSH_flag_count,flow_ACK_flag_count,fwd_URG_flag_count,bwd_URG_flag_count,flow_CWR_flag_count,flow_ECE_flag_count,fwd_pkts_payload.min,fwd_pkts_payload.max,fwd_pkts_payload.tot,fwd_pkts_payload.avg,fwd_pkts_payload.std,bwd_pkts_payload.min,bwd_pkts_payload.max,bwd_pkts_payload.tot,bwd_pkts_payload.avg,bwd_pkts_payload.std,flow_pkts_payload.min,flow_pkts_payload.max,flow_pkts_payload.tot,flow_pkts_payload.avg,flow_pkts_payload.std,fwd_iat.min,fwd_iat.max,fwd_iat.tot,fwd_iat.avg,fwd_iat.std,bwd_iat.min,bwd_iat.max,bwd_iat.tot,bwd_iat.avg,bwd_iat.std,flow_iat.min,flow_iat.max,flow_iat.tot,flow_iat.avg,flow_iat.std,payload_bytes_per_second,fwd_subflow_pkts,bwd_subflow_pkts,fwd_subflow_bytes,bwd_subflow_bytes,fwd_bulk_bytes,bwd_bulk_bytes,fwd_bulk_packets,bwd_bulk_packets,fwd_bulk_rate,bwd_bulk_rate,active.min,active.max,active.tot,active.avg,active.std,idle.min,idle.max,idle.tot,idle.avg,idle.std,fwd_init_window_size,bwd_init_window_size,fwd_last_window_size
count,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,1.231170e+05,1.231170e+05,1.231170e+05,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.0,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,123117.000000,1.231170e+05,123117.000000,123117.000000,123117.000000,123117.000000,1.231170e+05,123117.000000,123117.000000,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,123117.000000,123117.000000,123117.000000,1.231170e+05,123117.000000,1.231170e+05,123117.000000,123117.000000,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,1.231170e+05,123117.000000,123117.000000,123117.000000
mean,3.809566,2.268826,1.909509,1.471218,0.820260,3.518063e+05,3.517620e+05,7.035683e+05,0.854571,53.892379,19.779397,20.646637,46.626900,17.695915,18.432678,0.115605,0.950868,0.796454,0.351332,0.393634,2.677737,0.016293,0.0,0.001007,0.000699,96.256073,120.749133,221.519108,100.523827,8.107768,3.817523,52.405005,5.129981e+02,18.786782,20.553025,13.554440,148.510904,7.345172e+02,65.010194,76.041654,8.843266e+03,1.721566e+06,3.780208e+06,2.373575e+05,5.775574e+05,3.764849e+03,4.077267e+05,1.779893e+06,8.765213e+04,1.474803e+05,4.283079e+03,1.725999e+06,3.810575e+06,1.396545e+05,4.501362e+05,4.105345e+07,1.551715,1.337718,136.479504,2.175178e+02,19.249937,1.552337e+02,0.024144,0.131113,3.835746e+03,4.841460e+04,1.331546e+05,1.785898e+05,2.929308e+05,1.481354e+05,2.353599e+04,1.616655e+06,1.701956e+06,3.517644e+06,1.664985e+06,4.550183e+04,6118.905123,2739.776018,751.647514
std,130.005408,22.336565,33.018311,19.635196,32.293948,3.707645e+05,3.708015e+05,7.415634e+05,0.337640,393.027195,5.347869,7.230706,1028.228573,7.997577,9.406320,0.475013,0.474262,0.436998,3.951627,6.007443,41.654868,0.126602,0.0,0.044689,0.031471,45.274996,121.299738,4820.400607,46.097816,45.041897,19.611200,231.305346,4.244143e+04,83.483058,93.397596,35.472227,218.232399,4.296599e+04,50.412145,74.019903,1.226521e+06,9.229085e+06,1.299675e+08,1.895354e+06,3.204813e+06,2.263147e+05,4.288636e+06,9.121196e+07,1.097456e+06,1.784791e+06,2.544910e+05,9.250249e+06,1.300057e+08,8.748026e+05,2.506220e+06,4.485706e+07,2.716957,6.007413,428.905357,7.580753e+03,1974.617810,1.959295e+04,1.484759,14.546545,3.080334e+05,6.852480e+05,1.042332e+06,3.011784e+06,1.445279e+07,1.613007e+06,1.477935e+06,8.809396e+06,9.252337e+06,1.229508e+08,9.007064e+06,1.091361e+06,18716.313861,10018.848534,6310.183843
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
25%,0.000001,1.000000,1.000000,1.000000,0.000000,7.454354e+01,7.288927e+01,1.490871e+02,1.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,120.000000,120.000000,120.000000,120.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,120.000000,1.200000e+02,60.000000,50.219518,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.536740e-01,9.536740e-01,9.536740e-01,9.536740e-01,0.000000e+00,2.580981e+03,1.000000,1.000000,120.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,9.536740e-01,9.536740e-01,9.536740e-01,9.536740e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,64.000000,0.000000,64.000000
50%,0.000004,1.000000,1.000000,1.000000,0.000000,2.467238e+05,2.467238e+05,4.934475e+05,1.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,120.000000,120.000000,120.000000,120.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,120.000000,1.200000e+02,60.000000,84.852814,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.814697e+00,4.053116e+00,4.053116e+00,4.053116e+00,0.000000e+00,2.960685e+07,1.000000,1.000000,120.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,4.053116e+00,4.053116e+00,4.053116e+00,4.053116e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,64.000000,0.000000,64.000000
75%,0.000005,1.000000,1.000000,1.000000,0.000000,5.242880e+05,5.242880e+05,1.048576e+06,1.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,120.000000,120.000000,120.000000,120.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,120.000000,1.200000e+02,60.000000,84.852814,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.006790e+00,5.006790e+00,5.006790e+00,5.006790e+00,0.000000e+00,5.592405e+07,1.000000,1.000000,120.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,5.006790e+00,5.006790e+00,5.006790e+00,5.006790e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,64.000000,0.000000,64.000000
max,21728.335578,4345.000000,10112.000000,4345.000000,10105.000000,1.048576e+06,1.048576e+06,2.097152e+06,6.087899,69296.000000,44.000000,52.000000,323592.000000,40.000000,44.000000,10.000000,8.000000,10.000000,864.000000,1446.000000,11772.000000,1.000000,0.0,4.000000,4.000000,1097.000000,1420.000000,747340.000000,1319.365439,731.579342,1357.000000,5124.000000,1.361042e+07,1457.052632,1506.011875,1097.000000,5124.000000,1.361058e+07,1156.084685,924.651958,3.002526e+08,3.002526e+08,2.172834e+10,3.002526e+08,2.122965e+08,4.319622e+07,3.000282e+08,1.876117e+10,1.501489e+08,2.119613e+08,4.351004e+07,3.000000e+08,2.172834e+10,7.283576e+07,1.341221e+08,1.258291e+08,276.833333,1685.333333,52067.750000,2.268402e+06,465095.000000,6.805208e+06,343.000000,5052.500000,4.633628e+07,2.830087e+07,3.125080e+08,8.480979e+08,2.945221e+09,4.374931e+08,4.774862e+08,3.000000e+08,3.000000e+08,2.096777e+10,3.000000e+08,1.208029e+08,65535.000000,65535.000000,65535.000000

In [97]:
(df[['fwd_pkts_tot', 'bwd_pkts_tot', 'fwd_data_pkts_tot', 'bwd_data_pkts_tot']] == 0).sum()

fwd_pkts_tot             44
bwd_pkts_tot          15228
fwd_data_pkts_tot      6807
bwd_data_pkts_tot    105597
dtype: int64

In [104]:
print(pd.crosstab(df['Attack_type'], df['proto']))

proto                       icmp    tcp   udp
Attack_type
ARP_poisioning                 8   1927  5815
DDOS_Slowloris                 0    529     5
DOS_SYN_Hping                  0  94659     0
MQTT_Publish                   0   4146     0
Metasploit_Brute_Force_SSH     0     29     8
NMAP_FIN_SCAN                  0     25     3
NMAP_OS_DETECTION              0   2000     0
NMAP_TCP_scan                  0   1002     0
NMAP_UDP_SCAN                  2    142  2446
NMAP_XMAS_TREE_SCAN            0   2007     3
Thing_Speak                   45   3779  4284
Wipro_bulb                     2    182    69

In [105]:
print(pd.crosstab(df['Attack_type'], df['service']))

service                         -  dhcp   dns  http  irc  mqtt  ntp  radius  \
Attack_type
ARP_poisioning                546    26  5583   129    0     0    7       0
DDOS_Slowloris                  6     2     3   523    0     0    0       0
DOS_SYN_Hping               94659     0     0     0    0     0    0       0
MQTT_Publish                   11     0     0     3    0  4132    0       0
Metasploit_Brute_Force_SSH      0     0     8     1    0     0    0       0
NMAP_FIN_SCAN                  24     0     3     1    0     0    0       0
NMAP_OS_DETECTION            2000     0     0     0    0     0    0       0
NMAP_TCP_scan                1002     0     0     0    0     0    0       0
NMAP_UDP_SCAN                2411     3    31   139    0     0    4       2
NMAP_XMAS_TREE_SCAN          2006     0     3     1    0     0    0       0
Thing_Speak                   151    14  4069  2667    0     0  110       0
Wipro_bulb                     45     5    53     0   43     0    0       0

service                     ssh   ssl
Attack_type
ARP_poisioning                0  1459
DDOS_Slowloris                0     0
DOS_SYN_Hping                 0     0
MQTT_Publish                  0     0
Metasploit_Brute_Force_SSH   28     0
NMAP_FIN_SCAN                 0     0
NMAP_OS_DETECTION             0     0
NMAP_TCP_scan                 0     0
NMAP_UDP_SCAN                 0     0
NMAP_XMAS_TREE_SCAN           0     0
Thing_Speak                   0  1097
Wipro_bulb                    0   107